### ISSUE TITLE
struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by mr-manuel** [gavinying/modpoll#10]
Hello,

thanks for this great piece of code!

Unfortunately I have a small problem, when writing data to Modbus. The value is received, but when publishing to Modbus something goes wrong.

```
2023-02-27 15:05:41,676 | I | modpoll.mqtt_task | Receive message (modpoll/must-ph18-5548-plus/set): b'{"object_type": "holding_register","address": 101011,"value": 570}'
2023-02-27 15:05:48,077 | I | modpoll.modbus_task | Writing register(s): device=must-ph18-5548-plus, address=101011, value=570
Traceback (most recent call last):
  File "/usr/bin/modpoll", line 8, in <module>
    sys.exit(app())
  File "/usr/lib/python3.8/site-packages/modpoll/main.py", line 100, in app
    modbus_write_register(device_name, reg["address"], reg["value"])
  File "/usr/lib/python3.8/site-packages/modpoll/modbus_task.py", line 422, in modbus_write_register
    result = master.write_register(address, value, slave=d.devid)
  File "/usr/lib/python3.8/site-packages/pymodbus/client/mixin.py", line 148, in write_register
    return self.execute(
  File "/usr/lib/python3.8/site-packages/pymodbus/client/base.py", line 192, in execute
    return self.transaction.execute(request)
  File "/usr/lib/python3.8/site-packages/pymodbus/transaction.py", line 159, in execute
    response, last_exception = self._transact(
  File "/usr/lib/python3.8/site-packages/pymodbus/transaction.py", line 273, in _transact
    packet = self.client.framer.buildPacket(packet)
  File "/usr/lib/python3.8/site-packages/pymodbus/framer/rtu_framer.py", line 245, in buildPacket
    data = message.encode()
  File "/usr/lib/python3.8/site-packages/pymodbus/register_write_message.py", line 35, in encode
    packet = struct.pack(">H", self.address)
struct.error: 'H' format requires 0 <= number <= 65535
```

Can you help me with that?

**Comment by mr-manuel** [comment]
I wrote a 0 to much in the address. `101011` instead of `10111`, so no script error :)
